#!/bin/bash

# install pip 19
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py

# install dependencies: numpy, math, xlsxwriter, random, itertools
pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose XlsxWriter